# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  release:
    tags: 
      - "*"

jobs:
  build:

    runs-on: ubuntu-latest
    
    
    
    steps:
    - name: Change to directory
    - run: cd FuckML.Library
    
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Pack
      run: dotnet pack --no-build --output --configuration Release
      
    - name: Set VERSION variable from tag
      run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
      
    - name: Push
      run: dotnet nuget push /bin/Release/FuckML.${VERSION}.nupkg --source https://nuget.pkg.github.com/${{ secrets.NUGET_USERNAME }}/index.json --api-key ${GITHUB_TOKEN}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
